-- Curriculum Navigator app schema for Supabase
-- Run in SQL Editor once on your Supabase project (idempotent — 재실행 안전).
--
-- ⚠ ADMIN_EMAIL / app_settings.admin_email 방식은 폐기됨 (2026-06).
--   관리자는 아래 admins 테이블로 식별하며, admins 테이블이 비어 있으면
--   앱이 "최초 관리자 등록" 화면을 자동으로 보여줌 — 별도 시드 데이터 불필요.

create extension if not exists pgcrypto;

create table if not exists public.app_settings (
  key text primary key,
  value text default ''
);

-- ── admins 테이블: DB 기반 관리자 식별 ───────────────────
-- 앱이 처음 배포된 곳에서는 이 테이블이 비어 있으므로, 프론트엔드가
-- admin_exists() 결과로 "최초 관리자 등록" 화면을 보여준다.
create table if not exists public.admins (
  email       text primary key,
  name        text not null default '',
  auth_method text not null default 'email', -- 'google' | 'email'
  created_at  timestamptz not null default now()
);

-- is_admin(): admins 테이블에 등록된 계정인지 확인 (다른 테이블의 RLS 정책에서 참조)
-- ⚠ set row_security = off 필수: SECURITY DEFINER만으로는 부족하다. 이 함수 없이
--   admins_bootstrap_insert 정책의 WITH CHECK가 "select 1 from admins" 같은 일반
--   서브쿼리를 직접 쓰면, 그 서브쿼리는 호출한 role(anon/authenticated) 권한으로
--   실행되어 admins_self_or_admin_read SELECT 정책이 다시 적용되고, 그 정책이 다시
--   is_admin()을 호출하면서 무한 재귀(`infinite recursion detected in policy for
--   relation "admins"`, 42P17)에 빠진다. row_security = off는 이 함수 소유자
--   (postgres, bypassrls)가 내부 조회 시 RLS를 절대 다시 적용하지 않도록 못박아
--   재귀 경로를 원천적으로 끊는다.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select exists (
    select 1 from public.admins a
    where lower(a.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

-- admin_exists(): 관리자가 한 명도 없는지 여부만 노출 (로그인 전 anon 호출용)
-- ⚠ is_admin()과 동일한 이유로 row_security = off 필요.
create or replace function public.admin_exists()
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select exists (select 1 from public.admins);
$$;

revoke all on function public.admin_exists() from public;
grant execute on function public.admin_exists() to anon, authenticated;

alter table public.admins enable row level security;

-- admins: 본인 행 읽기 + 관리자는 전체 읽기 (회원관리 화면에서 관리자 목록 표시용)
drop policy if exists admins_self_or_admin_read on public.admins;
create policy admins_self_or_admin_read
on public.admins
for select
to authenticated
using (
  lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  or (select public.is_admin())
);

-- admins: 테이블이 완전히 비어 있을 때만 누구나(최초 1명) 등록 가능 (부트스트랩)
-- ⚠ with check에 "not exists (select 1 from public.admins)"처럼 admins를 직접
--   서브쿼리로 건드리면 안 된다 — 그 서브쿼리는 INSERT를 실행하는 role(anon/
--   authenticated) 권한으로 평가되어 admins_self_or_admin_read SELECT 정책을
--   다시 트리거하고, 그 정책이 is_admin()을 호출하며 다시 admins를 들여다보는
--   순환이 생겨 "infinite recursion detected in policy for relation admins"
--   (42P17) 에러가 난다. admin_exists()(SECURITY DEFINER + row_security off)를
--   통해서만 존재 여부를 확인해야 이 순환이 끊어진다.
drop policy if exists admins_bootstrap_insert on public.admins;
create policy admins_bootstrap_insert
on public.admins
for insert
to anon, authenticated
with check (not public.admin_exists());

grant select on public.admins to authenticated;
grant insert on public.admins to anon, authenticated;

create table if not exists public.teacher_emails (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.semester_courses (
  id bigint generated by default as identity primary key,
  cohort_year integer,
  semester text not null,
  name text not null,
  area text not null,
  type text not null,
  group_name text not null,
  pick integer not null default 0,
  credit numeric not null default 0,
  sort_order integer
);

-- 기존 배포본에는 cohort_year가 없었으므로 새 배포/재실행 모두 안전하게 보강한다.
alter table public.semester_courses
  add column if not exists cohort_year integer;

-- 코호트별 교육과정에서는 같은 학기·그룹·과목명이 입학년도마다 반복될 수 있다.
-- 예전 유니크 키(semester, group_name, name)는 코호트 자료 업로드 시 충돌을 만들 수
-- 있으므로 cohort_year를 포함한 키로 교체한다.
drop index if exists semester_courses_unique_key;
create unique index if not exists semester_courses_unique_key
  on public.semester_courses (cohort_year, semester, group_name, name);

create table if not exists public.university_recommendations (
  id bigint generated by default as identity primary key,
  university text not null,
  region_area text,
  series text,
  department text,
  detail_department text,
  tags text,
  core text,
  recommended text,
  reflected text,
  note text,
  sort_order integer
);

-- 계열별 대표 모집단위별 반영과목 매트릭스 (university-recommendations-series.xlsx "반영과목" 시트)
-- 16개 대표 (계열,모집단위)별 대학명 + 그 대학이 반영(요구)하는 과목 목록(파이프 구분)
create table if not exists public.series_reflected_matrix (
  id bigint generated by default as identity primary key,
  series text not null,
  department text not null,
  university text not null,
  required_subjects text,
  sort_order integer
);

create table if not exists public.links (
  id bigint generated by default as identity primary key,
  category text,
  name text not null,
  url text not null,
  description text,
  tags text,
  sort_order integer
);

create table if not exists public.subject_examples (
  id bigint generated by default as identity primary key,
  series text not null,
  department text not null,
  similar_departments text,
  subjects text,
  sort_order integer
);

create unique index if not exists subject_examples_unique_key
  on public.subject_examples (series, department);

-- ── 재배포 가능한 기본 설정값 ─────────────────────────────
-- 최초 관리자가 화면에서 바꿀 수 있거나, 새 학교가 SQL 실행 직후 바로 이해 가능한 기본값.
insert into public.app_settings (key, value) values
  ('app_name', '교육과정 탐색'),
  ('school_name', ''),
  ('current_academic_year', extract(year from now())::text),
  ('recommendation_source_year', '2028'),
  ('id_suffix', 'ckfqhfl'),
  ('school_domain_enabled', 'true'),
  ('school_domain', ''),
  ('google_domain', '')
on conflict (key) do nothing;

create table if not exists public.student_selections (
  email      text primary key,
  name       text not null default '',
  grade      text not null default '',   -- 학년 (1~3)
  class_no   text not null default '',   -- 반
  number     text not null default '',   -- 번호
  selected_map jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 기존 테이블에 컬럼 추가 (idempotent)
do $$
begin
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='student_selections' and column_name='grade') then
    alter table public.student_selections add column grade text not null default '';
  end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='student_selections' and column_name='class_no') then
    alter table public.student_selections add column class_no text not null default '';
  end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='student_selections' and column_name='number') then
    alter table public.student_selections add column number text not null default '';
  end if;
end $$;

create index if not exists student_selections_email_idx
  on public.student_selections (email);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_touch_student_selections on public.student_selections;
create trigger trg_touch_student_selections
before update on public.student_selections
for each row execute function public.touch_updated_at();

-- ── 교사 신청 테이블 ──────────────────────────────────────
-- 교사가 관리자 승인 전에 신청 정보를 제출하는 테이블.
-- 익명(anon) 사용자도 insert 가능하도록 정책 설정.
create table if not exists public.teacher_requests (
  id           uuid        default gen_random_uuid() primary key,
  email        text        not null,
  name         text        not null,
  subject_area text        not null default '',  -- 담당 교과군
  auth_method  text        not null default 'google', -- 'google' | 'email'
  message      text        default '',
  status       text        not null default 'pending', -- 'pending' | 'approved' | 'rejected'
  portal_url   text        not null default '',  -- 실제 수강신청/결과 확인 개인별 웹주소(학생-교사정보.xlsx의 URL 열)
  homeroom_grade text      not null default '',  -- 담당 학년('1'|'2'|'3'). 비어 있으면 담임/부장 아님(제한 없음)
  homeroom_class text      not null default '',  -- 담임 학급 반 번호. 비어있거나 '0'이면 학년부장(비담임)
  created_at   timestamptz not null default now(),
  reviewed_at  timestamptz
);

-- 기존 테이블에 컬럼 추가 (idempotent)
do $$
begin
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='teacher_requests' and column_name='subject_area') then
    alter table public.teacher_requests add column subject_area text not null default '';
  end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='teacher_requests' and column_name='auth_method') then
    alter table public.teacher_requests add column auth_method text not null default 'google';
  end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='teacher_requests' and column_name='portal_url') then
    alter table public.teacher_requests add column portal_url text not null default '';
  end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='teacher_requests' and column_name='homeroom_grade') then
    alter table public.teacher_requests add column homeroom_grade text not null default '';
  end if;
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='teacher_requests' and column_name='homeroom_class') then
    alter table public.teacher_requests add column homeroom_class text not null default '';
  end if;
end $$;

create unique index if not exists teacher_requests_email_idx
  on public.teacher_requests (lower(email));

-- ── teacher role checker used in RLS ────────────────────
create or replace function public.is_teacher()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.teacher_emails t
    where lower(t.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_teacher() from public;
grant execute on function public.is_teacher() to authenticated;

-- ── API grants ───────────────────────────────────────────
grant usage on schema public to anon, authenticated;
grant select on public.semester_courses to authenticated;
grant select on public.university_recommendations to authenticated;
grant select on public.series_reflected_matrix to authenticated;
-- links(참고사이트): 비회원(게스트) 입장(2026-07 추가)이 Supabase 로그인 없이 anon key로
-- 직접 조회하므로 anon에도 read 권한이 필요하다(app_settings와 동일한 패턴).
grant select on public.links to anon, authenticated;
grant select on public.subject_examples to authenticated;
grant select on public.app_settings to authenticated;
grant select on public.teacher_emails to authenticated;
-- 관리자: teacher_emails insert/delete, teacher_requests 전체 관리
grant insert, delete on public.teacher_emails to authenticated;
grant select, insert, update on public.teacher_requests to authenticated;
-- 익명: teacher_requests insert (교사 신청 폼)
grant insert on public.teacher_requests to anon;
grant select, insert, update on public.student_selections to authenticated;

-- ── RLS ──────────────────────────────────────────────────
alter table public.app_settings enable row level security;
alter table public.teacher_emails enable row level security;
alter table public.teacher_requests enable row level security;
alter table public.semester_courses enable row level security;
alter table public.university_recommendations enable row level security;
alter table public.series_reflected_matrix enable row level security;
alter table public.links enable row level security;
alter table public.subject_examples enable row level security;
alter table public.student_selections enable row level security;

drop policy if exists app_settings_read on public.app_settings;
create policy app_settings_read
on public.app_settings
for select
to authenticated
using (true);

-- teacher_emails: 본인 이메일 읽기 (승인 여부 확인용)
drop policy if exists teacher_emails_self_read on public.teacher_emails;
create policy teacher_emails_self_read
on public.teacher_emails
for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- teacher_emails: 관리자 전체 읽기
drop policy if exists teacher_emails_admin_read on public.teacher_emails;
create policy teacher_emails_admin_read
on public.teacher_emails
for select
to authenticated
using ((select public.is_admin()));

-- teacher_emails: 관리자만 insert (교사 승인)
drop policy if exists teacher_emails_admin_insert on public.teacher_emails;
create policy teacher_emails_admin_insert
on public.teacher_emails
for insert
to authenticated
with check ((select public.is_admin()));

-- teacher_emails: 관리자만 delete (교사 제거)
drop policy if exists teacher_emails_admin_delete on public.teacher_emails;
create policy teacher_emails_admin_delete
on public.teacher_emails
for delete
to authenticated
using ((select public.is_admin()));

-- teacher_requests: 누구나 insert (교사 신청 폼, 인증 불필요)
drop policy if exists teacher_requests_anon_insert on public.teacher_requests;
create policy teacher_requests_anon_insert
on public.teacher_requests
for insert
to anon
with check (true);

-- teacher_requests: 관리자 전체 접근
drop policy if exists teacher_requests_admin_all on public.teacher_requests;
create policy teacher_requests_admin_all
on public.teacher_requests
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- teacher_requests: 본인 신청 내역 읽기 (2026-07 추가 — 로그인 헤더의 "수강신청 바로가기"
-- 버튼이 본인 portal_url을 읽을 수 있어야 함. student_requests_self_read와 동일 패턴)
drop policy if exists teacher_requests_self_read on public.teacher_requests;
create policy teacher_requests_self_read
on public.teacher_requests
for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- ⚠ 아래 semester_courses/university_recommendations/series_reflected_matrix/
-- subject_examples 네 정책의 `coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) =
-- false` 조건은 한때 "비회원(게스트) 입장"을 Supabase 익명 로그인(Anonymous Sign-Ins)으로
-- 구현했을 때 추가된 것이다.
-- 이후 게스트 기능은 Supabase 로그인을 아예 만들지 않는 방식(아래 links_read의 anon 허용
-- 참고)으로 다시 구현되어 이 조건은 더 이상 도달할 수 없는 조건이지만(이 앱은 익명 로그인을
-- 만들지 않으므로 is_anonymous가 참인 세션 자체가 없음), 남겨둬도 해가 없는 방어적 조건이라
-- 그대로 둔다.
drop policy if exists semester_courses_read on public.semester_courses;
create policy semester_courses_read
on public.semester_courses
for select
to authenticated
using (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

drop policy if exists university_recommendations_read on public.university_recommendations;
create policy university_recommendations_read
on public.university_recommendations
for select
to authenticated
using (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

drop policy if exists series_reflected_matrix_read on public.series_reflected_matrix;
create policy series_reflected_matrix_read
on public.series_reflected_matrix
for select
to authenticated
using (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

-- links(참고사이트): 비회원(게스트) 입장(2026-07 추가, Supabase 로그인 없이 anon key로
-- 직접 조회)도 볼 수 있어야 하므로 유일하게 `to anon`도 포함한다.
drop policy if exists links_read on public.links;
create policy links_read
on public.links
for select
to anon, authenticated
using (true);

drop policy if exists subject_examples_read on public.subject_examples;
create policy subject_examples_read
on public.subject_examples
for select
to authenticated
using (coalesce((auth.jwt() ->> 'is_anonymous')::boolean, false) = false);

drop policy if exists student_selections_self_read on public.student_selections;
create policy student_selections_self_read
on public.student_selections
for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists student_selections_teacher_read on public.student_selections;
create policy student_selections_teacher_read
on public.student_selections
for select
to authenticated
using ((select public.is_teacher()));

drop policy if exists student_selections_self_insert on public.student_selections;
create policy student_selections_self_insert
on public.student_selections
for insert
to authenticated
with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists student_selections_self_update on public.student_selections;
create policy student_selections_self_update
on public.student_selections
for update
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- student_selections: 관리자 전체 읽기
drop policy if exists student_selections_admin_read on public.student_selections;
create policy student_selections_admin_read
on public.student_selections
for select
to authenticated
using ((select public.is_admin()));

-- student_selections: 관리자 전체 수정 (학생 정보 + 선택과목 직접 편집)
drop policy if exists student_selections_admin_update on public.student_selections;
create policy student_selections_admin_update
on public.student_selections
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- student_selections: 관리자 전체 삽입
-- ⚠ adminUpdateStudent()는 upsert를 쓰는데, 승인은 됐지만 한 번도 과목 선택을
-- 저장하지 않아 student_selections에 아직 행이 없는 학생을 수정할 때는 upsert가
-- 실제로 INSERT로 동작한다. 이 정책이 없으면 student_selections_self_insert
-- (본인 이메일 일치 조건)만 적용되어, 관리자 이메일 ≠ 학생 이메일이라 INSERT가
-- "new row violates row-level security policy"로 막힌다.
drop policy if exists student_selections_admin_insert on public.student_selections;
create policy student_selections_admin_insert
on public.student_selections
for insert
to authenticated
with check ((select public.is_admin()));

-- teacher_requests: 인증된 사용자도 insert 가능 (이메일/비밀번호 교사 신청)
drop policy if exists teacher_requests_auth_insert on public.teacher_requests;
create policy teacher_requests_auth_insert
on public.teacher_requests
for insert
to authenticated
with check (true);

-- ══════════════════════════════════════════════════════════
--  회원가입 승인제 전환 (학생 가입 신청)
--  2026-06 추가분. ADMIN_EMAIL 환경변수 및 구글 학교계정 자동승인을 대체.
--  Google 로그인 코드 자체는 유지하되, 화면에서는 숨김 처리(프론트엔드).
--  (admins 테이블 / is_admin() / admin_exists()는 파일 상단으로 이동됨)
-- ══════════════════════════════════════════════════════════

-- ── student_emails 테이블: 학생 허용목록 (teacher_emails와 동일 패턴) ──
create table if not exists public.student_emails (
  email      text primary key,
  created_at timestamptz not null default now()
);

create or replace function public.is_student()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.student_emails s
    where lower(s.email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_student() from public;
grant execute on function public.is_student() to authenticated;

alter table public.student_emails enable row level security;

drop policy if exists student_emails_self_read on public.student_emails;
create policy student_emails_self_read
on public.student_emails
for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

drop policy if exists student_emails_admin_read on public.student_emails;
create policy student_emails_admin_read
on public.student_emails
for select
to authenticated
using ((select public.is_admin()));

drop policy if exists student_emails_admin_insert on public.student_emails;
create policy student_emails_admin_insert
on public.student_emails
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists student_emails_admin_delete on public.student_emails;
create policy student_emails_admin_delete
on public.student_emails
for delete
to authenticated
using ((select public.is_admin()));

grant select on public.student_emails to authenticated;
grant insert, delete on public.student_emails to authenticated;

-- ── student_requests 테이블: 학생 가입 신청 (teacher_requests와 동일 패턴) ──
create table if not exists public.student_requests (
  id          uuid        default gen_random_uuid() primary key,
  email       text        not null,
  name        text        not null,
  grade       text        not null default '',
  class_no    text        not null default '',
  number      text        not null default '',
  auth_method text        not null default 'email', -- 'google' | 'email'
  message     text        default '',
  status      text        not null default 'pending', -- 'pending' | 'approved' | 'rejected'
  portal_url  text        not null default '',  -- 실제 수강신청/결과 확인 개인별 웹주소(학생-교사정보.xlsx의 URL 열)
  created_at  timestamptz not null default now(),
  reviewed_at timestamptz
);

-- 기존 테이블에 컬럼 추가 (idempotent)
do $$
begin
  if not exists (select 1 from information_schema.columns
                 where table_schema='public' and table_name='student_requests' and column_name='portal_url') then
    alter table public.student_requests add column portal_url text not null default '';
  end if;
end $$;

create unique index if not exists student_requests_email_idx
  on public.student_requests (lower(email));

alter table public.student_requests enable row level security;

-- student_requests: 누구나 insert (학생 가입 신청 폼, 인증 불필요)
drop policy if exists student_requests_anon_insert on public.student_requests;
create policy student_requests_anon_insert
on public.student_requests
for insert
to anon
with check (true);

-- student_requests: 인증된 사용자도 insert 가능 (가입 직후 세션이 생긴 경우)
drop policy if exists student_requests_auth_insert on public.student_requests;
create policy student_requests_auth_insert
on public.student_requests
for insert
to authenticated
with check (true);

-- student_requests: 본인 신청 내역 읽기 (승인 후 최초 로그인 시 학년·반·번호 자동 채움용)
drop policy if exists student_requests_self_read on public.student_requests;
create policy student_requests_self_read
on public.student_requests
for select
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));

-- student_requests: 관리자 전체 접근 (목록 조회 + 승인/거부 상태 변경)
drop policy if exists student_requests_admin_all on public.student_requests;
create policy student_requests_admin_all
on public.student_requests
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, insert, update on public.student_requests to authenticated;
grant insert on public.student_requests to anon;

-- ══════════════════════════════════════════════════════════
--  학교 도메인 자동승인 설정 (2026-06 추가)
--  최초 관리자 등록 화면에서 관리자가 "학교 도메인 사용 여부"와 "도메인 값"을
--  app_settings(school_domain_enabled / school_domain)에 저장한다.
--  사용 시: 가입 시 입력한 아이디(이메일) 또는 로그인한 Google 계정의 이메일이
--  해당 도메인과 일치하면 관리자 승인 없이 teacher_emails/student_emails에
--  본인이 직접(self-insert) 등록될 수 있다 (RLS로 강제).
-- ══════════════════════════════════════════════════════════

-- app_settings: 관리자만 쓰기 가능 (읽기는 anon도 허용 — 로그인 전 가입 화면에서 설정 확인 필요)
grant select on public.app_settings to anon;
grant insert, update on public.app_settings to authenticated;

drop policy if exists app_settings_read on public.app_settings;
create policy app_settings_read
on public.app_settings
for select
to anon, authenticated
using (true);

drop policy if exists app_settings_admin_write on public.app_settings;
create policy app_settings_admin_write
on public.app_settings
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists app_settings_admin_update on public.app_settings;
create policy app_settings_admin_update
on public.app_settings
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

-- school_domain_enabled(): app_settings.key='school_domain_enabled' 값이 'true'인지
create or replace function public.school_domain_enabled()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select value from public.app_settings where key = 'school_domain_enabled'),
    'false'
  ) = 'true';
$$;

revoke all on function public.school_domain_enabled() from public;
grant execute on function public.school_domain_enabled() to anon, authenticated;

-- school_domain_value(): app_settings.key='school_domain' 값
create or replace function public.school_domain_value()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (select value from public.app_settings where key = 'school_domain'),
    ''
  );
$$;

revoke all on function public.school_domain_value() from public;
grant execute on function public.school_domain_value() to anon, authenticated;

-- is_school_domain_email(): 도메인 사용이 켜져 있고, 주어진 이메일이 그 도메인으로 끝나는지
create or replace function public.is_school_domain_email(target_email text)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    public.school_domain_enabled()
    and length(public.school_domain_value()) > 0
    and lower(coalesce(target_email, '')) like ('%@' || lower(public.school_domain_value()));
$$;

revoke all on function public.is_school_domain_email(text) from public;
grant execute on function public.is_school_domain_email(text) to anon, authenticated;

-- ══════════════════════════════════════════════════════════
--  관리자 탭 "데이터 관리" — 교육과정(semester_courses) 엑셀 업로드
--  (2026-07 추가). 기존에는 semester_courses에 SELECT 정책만 있고
--  관리자용 INSERT/UPDATE/DELETE 정책이 없었음 — 로컬 Python 스크립트로
--  CSV를 만들어 Supabase 대시보드 SQL Editor에서 수동 실행하는 것만 지원되던
--  경로였기 때문(그 경로는 SQL Editor가 RLS를 우회하는 postgres 역할로 실행됨).
--  웹앱(관리자 탭 → 데이터 관리)에서 anon/authenticated 키로 직접 갱신하려면
--  is_admin() 기반 쓰기 정책이 필요함.
-- ══════════════════════════════════════════════════════════

grant insert, update, delete on public.semester_courses to authenticated;

drop policy if exists semester_courses_admin_insert on public.semester_courses;
create policy semester_courses_admin_insert
on public.semester_courses
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists semester_courses_admin_update on public.semester_courses;
create policy semester_courses_admin_update
on public.semester_courses
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists semester_courses_admin_delete on public.semester_courses;
create policy semester_courses_admin_delete
on public.semester_courses
for delete
to authenticated
using ((select public.is_admin()));

-- ══════════════════════════════════════════════════════════
--  관리자 탭 "데이터 관리" — 대학 추천과목(university_recommendations) +
--  계열별 대표 모집단위 반영과목(series_reflected_matrix) 엑셀 업로드 (2026-07 추가).
--  semester_courses와 동일한 이유로 관리자용 INSERT/UPDATE/DELETE 정책이 필요.
-- ══════════════════════════════════════════════════════════

grant insert, update, delete on public.university_recommendations to authenticated;

drop policy if exists university_recommendations_admin_insert on public.university_recommendations;
create policy university_recommendations_admin_insert
on public.university_recommendations
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists university_recommendations_admin_update on public.university_recommendations;
create policy university_recommendations_admin_update
on public.university_recommendations
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists university_recommendations_admin_delete on public.university_recommendations;
create policy university_recommendations_admin_delete
on public.university_recommendations
for delete
to authenticated
using ((select public.is_admin()));

grant insert, update, delete on public.series_reflected_matrix to authenticated;

drop policy if exists series_reflected_matrix_admin_insert on public.series_reflected_matrix;
create policy series_reflected_matrix_admin_insert
on public.series_reflected_matrix
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists series_reflected_matrix_admin_update on public.series_reflected_matrix;
create policy series_reflected_matrix_admin_update
on public.series_reflected_matrix
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists series_reflected_matrix_admin_delete on public.series_reflected_matrix;
create policy series_reflected_matrix_admin_delete
on public.series_reflected_matrix
for delete
to authenticated
using ((select public.is_admin()));

-- ══════════════════════════════════════════════════════════
--  관리자 탭 "데이터 관리" — 참고 사이트(links) 엑셀 업로드 (2026-07 추가).
--  다른 테이블과 동일한 이유로 관리자용 INSERT/UPDATE/DELETE 정책이 필요.
-- ══════════════════════════════════════════════════════════

grant insert, update, delete on public.links to authenticated;

drop policy if exists links_admin_insert on public.links;
create policy links_admin_insert
on public.links
for insert
to authenticated
with check ((select public.is_admin()));

drop policy if exists links_admin_update on public.links;
create policy links_admin_update
on public.links
for update
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists links_admin_delete on public.links;
create policy links_admin_delete
on public.links
for delete
to authenticated
using ((select public.is_admin()));

-- teacher_emails: 학교 도메인 일치 시 본인이 직접 등록(가입 즉시 승인)
drop policy if exists teacher_emails_self_domain_insert on public.teacher_emails;
create policy teacher_emails_self_domain_insert
on public.teacher_emails
for insert
to authenticated
with check (
  lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and public.is_school_domain_email(coalesce(auth.jwt() ->> 'email', ''))
);

-- student_emails: 학교 도메인 일치 시 본인이 직접 등록(가입 즉시 승인)
drop policy if exists student_emails_self_domain_insert on public.student_emails;
create policy student_emails_self_domain_insert
on public.student_emails
for insert
to authenticated
with check (
  lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  and public.is_school_domain_email(coalesce(auth.jwt() ->> 'email', ''))
);

-- ══════════════════════════════════════════════════════════
--  마이페이지 — 교사 본인 정보(이름/담당 교과) 수정 (2026-07 추가)
--  teacher_requests에는 그동안 관리자 전체 접근 정책과 본인 신청(insert)/본인 읽기 정책만
--  있었고, 교사 본인이 자신의 행을 update할 수 있는 정책이 없었다. "마이페이지" 탭에서
--  교사가 이름/담당 교과를 직접 수정할 수 있으려면 본인 이메일 행에 한해 update를
--  허용하는 정책이 필요하다(GRANT 자체는 위 teacher_requests 섹션에서 이미 부여됨).
--  (학생은 student_selections_self_update가 이미 있어 별도 정책 불필요.)
-- ══════════════════════════════════════════════════════════

drop policy if exists teacher_requests_self_update on public.teacher_requests;
create policy teacher_requests_self_update
on public.teacher_requests
for update
to authenticated
using (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')))
with check (lower(email) = lower(coalesce(auth.jwt() ->> 'email', '')));
